### ISSUE TITLE
Use Zoomable-View with ScrollView

### ISSUE THREAD

**Issue by Kasun-thilina** [DuDigital/react-native-zoomable-view-example#3]
Hi,
First of all, This is a really nice library. Thank you for creating it :)
I want to create a chart that is zoomable. But the problem is it's inside a scrollview. Is there a way to use this library with a scrollview? I tried triggering the scrollEnabled with the Event listeners of zoomable-view. But none of them seems to be working inside a scrollview.
Please give me a solution if you can

thanks :)

**Comment by KavinAVS** [comment]
Hey, did you find a solution?
